[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "java -jar app.jar"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.env]
PORT = "8080" 
