[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "java -jar app.jar"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.env]
PORT = "8080"
DATABASE_URL = "${RAILWAY_POSTGRESQL_URL}"
DATABASE_USERNAME = "${RAILWAY_POSTGRESQL_USERNAME}"
DATABASE_PASSWORD = "${RAILWAY_POSTGRESQL_PASSWORD}"
